require('lib.opts')
require('lib.autocmds')
require('lib.lsp')

require('lib.plugins.plenary')
require('lib.plugins.web-devicons')
require('lib.plugins.lspconfig')
require('lib.plugins.treesitter')
require('lib.plugins.snacks')
require('lib.plugins.git-blame')
require('lib.plugins.nvim-tree')
require('lib.plugins.gitsigns')
