require('opts')
require('autocmds')
require('lsp')

require('plugins.plenary')
require('plugins.web-devicons')
require('plugins.lspconfig')
require('plugins.treesitter')
require('plugins.snacks')
require('plugins.git-blame')
require('plugins.nvim-tree')
require('plugins.gitsigns')
require('plugins.aerial')
require('plugins.render-markdown')
